[tox]
skipsdist = True
envlist = py312

[testenv]
commands = pytest -vv --lf

deps = -rdev-requirements.txt

setenv =
  PYTHONPATH = {toxinidir}

[testenv:github-actions]
commands = pytest -vv --cov-report=html --cov-report=term-missing \
           --cov=app

deps = -rdev-requirements.txt

setenv =
  PYTHONPATH = {toxinidir}
